version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "5432:5432"                    
    volumes:
      - pgdata2:/var/lib/postgresql/data # Persist database data
      - ./db:/db
  app:
    build: .
    depends_on:
     - postgres
    network_mode: host
    env_file: ".env"

volumes:
  pgdata2:
